import './globals.css'
import { Inter } from 'next/font/google'
import Header from './header/page'
import Footer from './footer/page'
import NextAuthProvider from '@/component/Providers'
import Head from 'next/head';
import { Providers } from "@/redux/provider";
import ReactToast from '@/component/ReactToast'
const inter = Inter({ subsets: ['latin'] })
import localFont from 'next/font/local'
const bangla = localFont({src:'../public/fonts/bangla_normal.woff2'})
export const metadata = {
  title: 'Hello Next js',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Providers>
        <body className={`${inter.className} ${bangla.className}`}>
          <NextAuthProvider>
            <Header />
              {children}
            <ReactToast/>
          </NextAuthProvider>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js" async />
        </body>
      </Providers>
    </html>
  )
}
